name: workout_timer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.4+26

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sleek_circular_slider: ^2.0.0
  shared_preferences: ^2.0.5
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3
  share: ^2.0.1
  fl_chart: ^0.35.0
  back_button_interceptor: ^5.0.0
  wakelock: ^0.5.1
  focused_menu: ^1.0.5
  in_app_purchase: ^0.5.2
  flutter_displaymode: ^0.3.1-nullsafety.0
  json_annotation: ^4.0.1
  jiffy: ^5.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  plugin_platform_interface: ^2.0.0
  just_audio: ^0.9.18
  flutter_riverpod: ^1.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^6.1.3
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
    - assets/progressImg0.png
    - assets/progressImg1.jpg
    - assets/logoblender.png
    - assets/images/
    - assets/audio/amy/
    - assets/audio/brian/
    - assets/audio/emma/
    - assets/audio/joanna/
    - assets/audio/joey/
    - assets/audio/matthew/
    - assets/audio/olivia/
    - assets/audio/salli/
    - assets/audio/beep/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: Cursive
      fonts:
        - asset: assets/fonts/Yellowtail-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
